# Generated by Django 3.2 on 2021-04-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210410_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='dislikes',
            new_name='dislike',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='likes',
            new_name='like',
        ),
    ]
