# Generated by Django 3.2 on 2021-04-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210413_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
